---
- name: Dàn dựng hiện trường tấn công Insider Threat
  hosts: targets  # Đã mapping với groups 'targets' trong topology.yml
  become: yes
  tasks:
    - name: Tạo tài khoản sinh viên bị lộ mật khẩu
      user:
        name: student_test
        password: "$6$rounds=656000$SomeSalt$mF1/A.8v3y.a" # Đảm bảo hash không chứa ký tự đặc biệt làm gãy YAML
        shell: /bin/bash

    - name: Cài đặt công cụ và thiết lập SUID cho 'find'
      file:
        path: /usr/bin/find
        mode: '4755'

    - name: Giấu Flag 3
      copy:
        dest: /root/flag.txt
        content: "KYPO{suid_find_privesc_success}"
        mode: '0600'